"""add timestamp indexes on runs

Revision ID: 087ba3c1117b
Revises: 66dadb6f7481
Create Date: 2026-05-08 11:05:14.656634

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087ba3c1117b'
down_revision: Union[str, None] = '66dadb6f7481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_ended_at'), 'runs', ['ended_at'], unique=False)
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_ended_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    # ### end Alembic commands ###